/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package recoder.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaCCParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 10;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 11;
  /** RegularExpression Id. */
  int ABSTRACT = 13;
  /** RegularExpression Id. */
  int ASSERT = 14;
  /** RegularExpression Id. */
  int AT = 15;
  /** RegularExpression Id. */
  int BOOLEAN = 16;
  /** RegularExpression Id. */
  int BREAK = 17;
  /** RegularExpression Id. */
  int BYTE = 18;
  /** RegularExpression Id. */
  int CASE = 19;
  /** RegularExpression Id. */
  int CATCH = 20;
  /** RegularExpression Id. */
  int CHAR = 21;
  /** RegularExpression Id. */
  int CLASS = 22;
  /** RegularExpression Id. */
  int CONST = 23;
  /** RegularExpression Id. */
  int CONTINUE = 24;
  /** RegularExpression Id. */
  int _DEFAULT = 25;
  /** RegularExpression Id. */
  int DO = 26;
  /** RegularExpression Id. */
  int DOUBLE = 27;
  /** RegularExpression Id. */
  int ELSE = 28;
  /** RegularExpression Id. */
  int ENUM = 29;
  /** RegularExpression Id. */
  int EXTENDS = 30;
  /** RegularExpression Id. */
  int FALSE = 31;
  /** RegularExpression Id. */
  int FINAL = 32;
  /** RegularExpression Id. */
  int FINALLY = 33;
  /** RegularExpression Id. */
  int FLOAT = 34;
  /** RegularExpression Id. */
  int FOR = 35;
  /** RegularExpression Id. */
  int GOTO = 36;
  /** RegularExpression Id. */
  int IF = 37;
  /** RegularExpression Id. */
  int IMPLEMENTS = 38;
  /** RegularExpression Id. */
  int IMPORT = 39;
  /** RegularExpression Id. */
  int INSTANCEOF = 40;
  /** RegularExpression Id. */
  int INT = 41;
  /** RegularExpression Id. */
  int INTERFACE = 42;
  /** RegularExpression Id. */
  int LONG = 43;
  /** RegularExpression Id. */
  int NATIVE = 44;
  /** RegularExpression Id. */
  int NEW = 45;
  /** RegularExpression Id. */
  int NULL = 46;
  /** RegularExpression Id. */
  int PACKAGE = 47;
  /** RegularExpression Id. */
  int PRIVATE = 48;
  /** RegularExpression Id. */
  int PROTECTED = 49;
  /** RegularExpression Id. */
  int PUBLIC = 50;
  /** RegularExpression Id. */
  int RETURN = 51;
  /** RegularExpression Id. */
  int SHORT = 52;
  /** RegularExpression Id. */
  int STATIC = 53;
  /** RegularExpression Id. */
  int SUPER = 54;
  /** RegularExpression Id. */
  int SWITCH = 55;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 56;
  /** RegularExpression Id. */
  int THIS = 57;
  /** RegularExpression Id. */
  int THROW = 58;
  /** RegularExpression Id. */
  int THROWS = 59;
  /** RegularExpression Id. */
  int TRANSIENT = 60;
  /** RegularExpression Id. */
  int TRUE = 61;
  /** RegularExpression Id. */
  int TRY = 62;
  /** RegularExpression Id. */
  int VOID = 63;
  /** RegularExpression Id. */
  int VOLATILE = 64;
  /** RegularExpression Id. */
  int WHILE = 65;
  /** RegularExpression Id. */
  int VARARGDENOTER = 66;
  /** RegularExpression Id. */
  int STRICTFP = 67;
  /** RegularExpression Id. */
  int LONG_LITERAL = 68;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 69;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 70;
  /** RegularExpression Id. */
  int HEX_LITERAL = 71;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 72;
  /** RegularExpression Id. */
  int BINARY_LITERAL = 73;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 74;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 75;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 76;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 77;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 78;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 79;
  /** RegularExpression Id. */
  int STRING_LITERAL = 80;
  /** RegularExpression Id. */
  int IDENTIFIER = 81;
  /** RegularExpression Id. */
  int LETTER = 82;
  /** RegularExpression Id. */
  int PART_LETTER = 83;
  /** RegularExpression Id. */
  int LPAREN = 84;
  /** RegularExpression Id. */
  int RPAREN = 85;
  /** RegularExpression Id. */
  int LBRACE = 86;
  /** RegularExpression Id. */
  int RBRACE = 87;
  /** RegularExpression Id. */
  int LBRACKET = 88;
  /** RegularExpression Id. */
  int RBRACKET = 89;
  /** RegularExpression Id. */
  int SEMICOLON = 90;
  /** RegularExpression Id. */
  int COMMA = 91;
  /** RegularExpression Id. */
  int DOT = 92;
  /** RegularExpression Id. */
  int ASSIGN = 93;
  /** RegularExpression Id. */
  int LT = 94;
  /** RegularExpression Id. */
  int BANG = 95;
  /** RegularExpression Id. */
  int TILDE = 96;
  /** RegularExpression Id. */
  int HOOK = 97;
  /** RegularExpression Id. */
  int COLON = 98;
  /** RegularExpression Id. */
  int EQ = 99;
  /** RegularExpression Id. */
  int LE = 100;
  /** RegularExpression Id. */
  int GE = 101;
  /** RegularExpression Id. */
  int NE = 102;
  /** RegularExpression Id. */
  int SC_OR = 103;
  /** RegularExpression Id. */
  int SC_AND = 104;
  /** RegularExpression Id. */
  int INCR = 105;
  /** RegularExpression Id. */
  int DECR = 106;
  /** RegularExpression Id. */
  int PLUS = 107;
  /** RegularExpression Id. */
  int MINUS = 108;
  /** RegularExpression Id. */
  int STAR = 109;
  /** RegularExpression Id. */
  int SLASH = 110;
  /** RegularExpression Id. */
  int BIT_AND = 111;
  /** RegularExpression Id. */
  int BIT_OR = 112;
  /** RegularExpression Id. */
  int XOR = 113;
  /** RegularExpression Id. */
  int REM = 114;
  /** RegularExpression Id. */
  int LSHIFT = 115;
  /** RegularExpression Id. */
  int PLUSASSIGN = 116;
  /** RegularExpression Id. */
  int MINUSASSIGN = 117;
  /** RegularExpression Id. */
  int STARASSIGN = 118;
  /** RegularExpression Id. */
  int SLASHASSIGN = 119;
  /** RegularExpression Id. */
  int ANDASSIGN = 120;
  /** RegularExpression Id. */
  int ORASSIGN = 121;
  /** RegularExpression Id. */
  int XORASSIGN = 122;
  /** RegularExpression Id. */
  int REMASSIGN = 123;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 124;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 125;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 126;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 127;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 128;
  /** RegularExpression Id. */
  int GT = 129;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "\"abstract\"",
    "\"assert\"",
    "\"@\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"...\"",
    "\"strictfp\"",
    "<LONG_LITERAL>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<BINARY_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
  };

}
